# Generated by Django 3.2 on 2021-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion'), ('Appliances', 'Appliances')], max_length=15),
        ),
    ]
