# Generated by Django 3.2 on 2021-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Appliances', 'Appliances'), ('Fashion', 'Fashion')], max_length=15),
        ),
    ]
