# Generated by Django 3.2 on 2021-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='loading', upload_to='kdstore/offers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Appliances', 'Appliances'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=15),
        ),
    ]
