# Generated by Django 3.2 on 2021-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0005_auto_20210719_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offers',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics')], max_length=15),
        ),
    ]
