# Generated by Django 3.2 on 2021-07-23 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0007_auto_20210722_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
