# Generated by Django 3.2.5 on 2021-07-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdstore', '0008_auto_20210723_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Appliances', 'Appliances'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('Deliver', 'Deliver'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdstore.checkout')),
            ],
        ),
    ]
